version: '3'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - book_project_laravel_app_network

  test_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: test_${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    networks:
      - book_project_laravel_app_network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - book_project_laravel_app_network

  web:
    build: .
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - book_project_laravel_app_network

volumes:
  db_data:
  test_db_data:

networks:
  book_project_laravel_app_network:
    external: true
